HuggingFace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
]

apps/urls.py
from django.urls import include, path
from . import views

app_name = 'apps'

urlpatterns = [
    path("", views.index, name="index"),
    path('summarization/', views.summarize, name='summarize'),
    path('textgenerator/', views.textgenerator, name='textgenerator'),
    path('questions/', views.qa, name='qa'),
    path('classification/', views.sentimental, name='sentimental'),
    path('translation/', views.translate, name='translate'),
]

apps/models.py
from django.db import models

# Create your models here.

apps/views.py
from django.shortcuts import render, redirect
from . import predict


# Create your views here.

def index(request):
    return render(request, 'apps/index.html')
    
def summarize(request):
    if request.method == "POST":
        text = request.POST.get("abstract")
        conclude = predict.summarizetext(text)[0]['summary_text']
        return render(request, 'apps/summarize.html', {
            "conclude": conclude,
            "abstract": text,
        })
    return render(request,'apps/summarize.html')

def textgenerator(request):
    if request.method == "POST":
        prompt = request.POST.get("prompt")
        length = int(request.POST.get("length"))
        result = predict.generator(prompt, length)[0]['generated_text']
        return render(request, 'apps/generation.html', {
            "result": result,
            "text": prompt,
        })
    return render(request, 'apps/generation.html')

def qa(request):
    if request.method == "POST":
        question = request.POST.get("question")
        context = request.POST.get("context")
        result = predict.QA(context, question)
        return render(request, 'apps/questions.html',{
            "answer": result[0],
            "score": result[1],
            "question": question,
            "context": context,
        })
    return render(request, 'apps/questions.html')

def sentimental(request):
    if request.method == "POST":
        review = request.POST.get("review")
        result = predict.classification(review)
        mapping = {"LABEL_0":"Joy", 'LABEL_1': "Optimism", 'LABEL_2': "Anger", 'LABEL3': 'Sadness'}
        emotion = mapping[result[0]['label']]
        score = result[0]['score']
        return render(request, 'apps/sentimental.html',{
            "emotion": emotion,
            "score": round(result[0]['score'],3),
            "review": review,
        }) 
    return render(request, 'apps/sentimental.html')


def translate(request):
    if request.method == "POST":
        text = request.POST.get("text")
        result = predict.translation(text)
        return render(request, 'apps/translate.html',{
            "result": result[0]['translation_text'],
            "text": text,
        })
    return render(request, 'apps/translate.html')

apps/templates/apps/generation.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Text generation</h2>
<div class="container">
    <form action="{% url 'apps:textgenerator' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control jTextarea" id="jTextarea'" rows="5" name="prompt"
                placeholder="Write your text here..." required>{{ text }}</textarea>
        </div>
        Length: <input style="margin-top: 3em" type="number" placeholder="Max length" name="length" max="300"
            value="30">
        <br>
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
    {% if result %}
    Generated text: <textarea class="form-control jTextarea" id="jTextarea'" rows="3">{{ result }}</textarea>
    {% endif %}
</div>
<script>
    $("#001").addClass("active");
</script>
{% endblock %}

apps/templates/apps/index.html
{% extends "apps/layout.html" %}

{% block body %}

<section class="introduction">
	<h1 class="heading">Introduction</h1>
	<p>I&rsquo;m Fangyi Yu. You can call me Elaine.</p> 
    <p>I&rsquo;m a Machine Learning researcher who loves <strong>good algorithems</strong>, <strong>good food</strong>, and <strong>good people</strong>. I am currently a master's student in Computer Science at Ontario Tech University &#127464;&#127462; researching AI applications in CyberSecurity and working as a research assistant and teaching assistant.</p>
	<p>Apart from net security, I am passionate about Natural Language Processing. I'm excited to present this side project of me, the NLP web application, to the public. Feel free to connect with me if you are interested in my other works or have any job or research opportunities available.</p>
	<p><strong>Note: </strong>All applications on the navigation bar would load for a while since the machine learning models on the backend needs some time to converge on a CPU. Yeah, these models are not trained on a GPU or TPU unfortunately.</p>
</section>
<section class="location">
	<h1 class="heading">Where I&rsquo;m From</h1>
	<p>I&rsquo;m from China, specifically - Yingtan, a small city in the mid-south &#127464;&#127475; I have been living in Canada since September 2019 and start a family here; I love the spacious fields, the smell of the outdoors, and the people in Canada. 
</section>
<section class="questions">
	<h1 class="heading">More About Me</h1>
	<dl class="question-list">
		<dt class="question">What are your favorite hobbies?</dt>
		<dd class="answer">I&rsquo;m a huge traveller and a hiker, I also <strong>LOVE</strong> food. I&rsquo;m always trying new cuisine. Foodies unite!</dd>
		<dt class="question">What&rsquo;s your dream job?</dt>
		<dd class="answer">Realistically, a data scientist or a university professor. I also want to be a farmer, living with flowers, veggies, and animals! Yeah, maybe when I retire&#128541;</dd>
		<dt class="question">What&rsquo;s your background?</dt>
		<dd class="answer">I&rsquo;ve been programming since ten years ago when I did my bachelor's degree in Mathematics. Five years of job experience in banking and two years of technical job experience working as a research associate in getting my hands dirty with data, designing, building and deploying machine learning models.</dd>
		<dt class="question">Where have you been travelling to?</dt>
		<dd class="answer">I&rsquo;ve been to New Zealand, Australia, Spain, America, Mexico, Vietnam, Japan, Singapore, Malaysia, Fiji, Hongkong, Taiwan, Macao, Thailand, Canada, of course&#128521;  And many, many beautiful cities in China. I want to explore every spot of the Earth with my loved ones! Would be better if outside of the Earth!</dd>
	</dl>
</section>
<footer class="content-footer">
    <p class="body-copy">Say hi to me on these social networks:</p>
    <ul class="social">
        <li><a href="https://github.com/fangyiyu" target="_blank">Github</a></li>
        <li><a href="https://www.linkedin.com/in/fangyiyu/" target="_blank">Linkedin</a></li>
        <li><a href="mailto:yufangyi1@gmail.com" target="_blank">Gmail</a></li>
    </ul>
</footer>
{% endblock %} 

apps/templates/apps/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} NLP projects {% endblock %}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'apps/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'apps/starability-all.min.css' %}" />
    <link rel="shortcut icon" href="{% static 'apps/logo.ico' %}" />

    <!-- javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-custom navbar-mainbg">
        <a class="navbar-brand navbar-logo" href="{% url 'apps:index' %}">NLP Projects</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector">
                    <div class="left"></div>
                    <div class="right"></div>
                </div>
                <li class="nav-item" id="001">
                    <a class="nav-link" href="{% url 'apps:textgenerator' %}">Text Generator</a>
                </li>
                <li class="nav-item" id="003">
                    <a class="nav-link" href="{% url 'apps:summarize' %}">Text Summarization</a>
                </li>
                <li class="nav-item" id="004">
                    <a class="nav-link" href="{% url 'apps:qa' %}">Question Answering</a>
                </li>
                <li class="nav-item" id="005">
                    <a class="nav-link" href="{% url 'apps:sentimental' %}">Sentimental Analysis</a>
                </li>
                <li class="nav-item" id="006">
                    <a class="nav-link" href="{% url 'apps:translate' %}">Machine Translation</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class='wrapper'>
        {% block body %}

        {% endblock %}
    </div>
    <script src="{% static 'apps/custom.js' %}"></script>

</body>

</html>

apps/templates/apps/questions.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Question Answering</h2>
<div class="container">
    <form action="{% url 'apps:qa' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control jTextarea" id="jTextarea'" rows="5" name="context"
                placeholder="Write your context here..." required></textarea>
            <br>
            <textarea class="form-control jTextarea" id="jTextarea'" rows="1" name="question"
                placeholder="Write your question here..." required>{{ questtion }}</textarea>
        </div>
        <button class="btn btn-warning" type="submit">Submit</button>
</div>
</form>
{% if answer %}
Answer: <textarea class="form-control jTextarea" id="jTextarea'" rows="1">{{ answer }}</textarea>
<span><small>with confidence {{ score }}</small></span>
{% endif %}
<script>
    $("#004").addClass("active");
</script>

{% endblock %}

apps/templates/apps/sentimental.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Product Review Analysis</h2>
<div class="container">
    <br>
    <span>This is a roBERTa-base model trained on ~58M tweets and finetuned for emotion recognition.
        <br> The emotions are: Joy&#128516; Optimism&#128512; Sadness&#128532; and Anger&#128545;
    </span>
    <form action="{% url 'apps:sentimental' %}" method="POST">
        {% csrf_token %}
        <div class="form-group mt-3">
            <textarea class="form-control jTextarea" id="jTextarea'" rows="5" name="review"
                placeholder="Write your review here..." required>{{ review }}</textarea>
        </div>
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
    {% if emotion %}
    <span><b>Analysis result: </b></span>
    <div style="text-align: center;">{{ emotion }}</div>
    {% endif %}
</div>
<script>
    $("#005").addClass("active");
</script>
{% endblock %}

apps/templates/apps/summarize.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Text Summarization</h2>
<div class="container">
    <form action="{% url 'apps:summarize' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <textarea maxlength="512" class="form-control jTextarea" id="jTextarea'" rows="3" name="abstract"
                placeholder="Write your text here..." required>{{ abstract }}</textarea>
        </div>
        <button class="btn btn-warning" type="submit">Submit</button>
</div>
</form>
{% if conclude %}
Abstract: <textarea class="form-control jTextarea" id="jTextarea'" rows="1">{{ conclude }}</textarea>
{% endif %}
<script>
    $("#003").addClass("active");
</script>
{% endblock %}

apps/templates/apps/translate.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Machine Translation</h2>
<div class="container">
    <br><br>
    <span>A tool to translate English to French.</span>
    <form action="{% url 'apps:translate' %}" method="POST">
        {% csrf_token %}
        <div class="form-group mt-3">
            <textarea maxlength="215" class="form-control jTextarea" id="jTextarea'" rows="5" name="text"
                placeholder="Write your text here..." required>{{ text }}</textarea>
        </div>
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
    {% if result %}
    Translated text in French: <textarea class="form-control jTextarea" id="jTextarea'" rows="3">{{ result }}</textarea>
    {% endif %}

</div>
<script>
    $("#006").addClass("active");
</script>
{% endblock %}